// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(UnityOfWork))]
    [Migration("20200930032009_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.ContaAPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MultaAplicadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("QuantidadeDiasEmAtraso")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MultaAplicadaId");

                    b.ToTable("ContaAPagar");
                });

            modelBuilder.Entity("Domain.Entities.Multa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PeriodoMaximoDeDiasEmAtraso")
                        .HasColumnType("int");

                    b.Property<double>("PorcentagemAplicadaDiaAtraso")
                        .HasColumnType("float");

                    b.Property<double>("PorcentagemAplicadaMulta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Multa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("557256ce-83b3-4892-9acd-c8b03ed6a9de"),
                            PeriodoMaximoDeDiasEmAtraso = 3,
                            PorcentagemAplicadaDiaAtraso = 0.001,
                            PorcentagemAplicadaMulta = 0.02
                        },
                        new
                        {
                            Id = new Guid("6c9f40d0-89c4-4326-8b49-fa48cbaa521a"),
                            PeriodoMaximoDeDiasEmAtraso = 5,
                            PorcentagemAplicadaDiaAtraso = 0.002,
                            PorcentagemAplicadaMulta = 0.029999999999999999
                        },
                        new
                        {
                            Id = new Guid("538aafe5-4edf-4e0a-a629-67e36a1a11cb"),
                            PorcentagemAplicadaDiaAtraso = 0.0030000000000000001,
                            PorcentagemAplicadaMulta = 0.050000000000000003
                        });
                });

            modelBuilder.Entity("Domain.Entities.ContaAPagar", b =>
                {
                    b.HasOne("Domain.Entities.Multa", "MultaAplicada")
                        .WithMany()
                        .HasForeignKey("MultaAplicadaId");
                });
#pragma warning restore 612, 618
        }
    }
}
